//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : GaussianMixture library Untitled
//  @ File Name : GaussianMixture.h
//  @ Date : 2009-07-16
//  @ Author : Dominik Belter
//
//

#ifndef _APPROXIMATION_H
#define _APPROXIMATION_H

#include "../3rdParty/tinyXML/tinyxml2.h"
#include <iostream>

using namespace std;

namespace approximator
{

    class Approximation
    {
    public:
        /// Map type
        enum Type
        {
            /// Gaussian mixture approximator
            GAUSSIANMIXTURE,
        };

        /// overloaded constructor
        Approximation(const std::string _name, Type _type) : name(_name), type(_type) {
                                                             };

        /// Name of the map
        virtual const std::string &getName() const { return name; };

        /// Virtual descrutor
        virtual ~Approximation()
        {
        }

        /// search for the best GaussianMixture function - PSO method
        virtual void train() = 0;

    private:
        /// Map type
        Type type;

        /// Map name
        const std::string name;
    };
};

#endif //_APPROXIMATION_H
