//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Approximation library Untitled
//  @ File Name : recorder.h
//  @ Date : 2009-07-16
//  @ Author : Dominik Belter
//
//

#ifndef _RECORDER_H
#define _RECORDER_H
#include <iostream>
#include <list>

class Recorder
{
public:
	Recorder(void);
	~Recorder(void);
	/// save point
	void save(float value);
	/// set delay
	void setDelay(int value);
	/// save to file
	void save2file(const char *filename, const char *var_name);
	/// clear container
	void clearContainer(void);

	// variables
private:
	/// lista do przechowywania obiektow - macierzy jednorodnych okreslajacych pozycje i orientacje
	std::list<float> container;
	/// delay how many step are not saved
	int delay;
	/// delay iterator
	int delay_iterator;
};

#endif //_Population_H
